# Generated by Django 4.2 on 2023-04-10 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='respond',
            field=models.ManyToManyField(related_name='post_responses', through='board.ResponsePost', to=settings.AUTH_USER_MODEL),
        ),
    ]
